### ISSUE TITLE
Enum verwenden

### ISSUE THREAD

**Issue by theDigitalViking** [LucasRegalar/Expense-Tracker-V2#2]
https://github.com/LucasRegalar/Expense-Tracker-V2/blob/5db76bdf4d49853eb51d20bffaf964468eab6cb4/core/Responses.php#L5

Seit PHP 8 gibt es Enums, kannst du noch nicht kennen, ist aber genau für solche Cases.

**Comment by LucasRegalar** [comment]
Musst du mir Freitag nochmal genau erklären :)
