### ISSUE TITLE
Elternklasse in ganz anderem Namespace

### ISSUE THREAD

**Issue by theDigitalViking** [LucasRegalar/Expense-Tracker-V2#4]
https://github.com/LucasRegalar/Expense-Tracker-V2/blob/5db76bdf4d49853eb51d20bffaf964468eab6cb4/http/forms/AddTransForm.php#L7

Die Elternklasse ist in einem ganz anderen Namespace. Das hat viel mit persönlicher Präferenz und Struktur des Projekts zu tun. Ich persönlich würde die Elternklasse nach aktuellem Stand mit darein packen.

**Comment by LucasRegalar** [comment]
Habe mir schon gedacht, dass das evlt. nicht perfekt gelößt ist. Meine Überlegung war, die Form Klasse allgemeinn und reusable für spätere Projekte zu konstruieren und sie deswegen auch in den "core" ordner zu packen.

Aber du meinst, besser mit in http/forms?
